import { StyleSheet } from 'react-native';

// Style Definitions
export const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        padding: 20,
    },
    container2: {
        flex: 1, 
        flexDirection: 'row',
        zIndex: 10,
        justifyContent: "space-between",
        alignItems: "center",
    },
    container3: {
        flex: 1,
    },
    iconContainer: {
        marginRight: 10,
    },
    calendarContainer: {
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        marginBottom: 20,
    },
    buttonContainer: {
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    textTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
    },
    pageTitle: {
        fontSize: 30,
        fontWeight: 'bold',
    },
    questionText: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    titleNote: {
        fontSize: 16,
        color: '#979595',
    },
    button: {
        width: 170,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
        marginVertical: 10,
        marginBottom: 20,
    },
    button2: {
        width: 300,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#C2C7E3',
        marginVertical: 20,
    },
    button3: {
        width: 100,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
    },
    button4: {
        width: 320,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
    },
    button5: {
        width: 270,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
    },
    button6: {
        width: 80,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
    },
    button7: {
        width: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#d470af',
        marginRight: 10,
    },
    button8: {
        width: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
        marginRight: 10,
    },
    defaultButton: {
        borderColor: '#E3C2D7',
        backgroundColor: 'transparent',
        borderWidth: 1,
    },
    buttonPosition: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    input: {
        width: 320,
        height: 40,
        padding: 10,
        backgroundColor: '#D9D9D9',
    },
    input2: {
        width: 240,
        height: 30,
        padding: 10,
        borderWidth: 1,
    },
    input3: {
        width: 340,
        height: 40,
        padding: 10,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#979595', 
    },
    imgButton: {
        width: 120,
        height: 120,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderWidth: 1,
    },
    selectedImgButton: {
        width: 120,
        height: 120,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderWidth: 1,
        backgroundColor: '#D39FC0',
    },
    text: {
        fontSize: 16,
    },
    text2: {
        fontSize: 16,
        marginRight: 5,
    },
    formText: {
        fontSize: 16,
        color: '#979595',
    },
    buttonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#6BB4DE',
    },
    error: {
        color: 'red',
    },
    date: {
        fontSize: 20,
        color: '#979595',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 30,
    },
    dayLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        width: 30,
        textAlign: 'center',
    },
    days: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 30,
    },
    date2: {
        fontSize: 16,
        width: 30,
        textAlign: 'center',
    },
    currentDate: {
        color: '#d470af',
        fontWeight: "bold",
    },
    textInputWithIcon: {
        paddingLeft: 40, 
    },
    textInputWithIcon2: {
        paddingLeft: 60, 
    },
    search: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    categoryBtn: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 1,
      },
    categoryBtnActive: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#E3C2D7",
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 20,
    },
    categoryBtnTxt: {
        marginLeft: 5,
        color: "black",
    },
    resourceBtn: {
        borderWidth: 1,
        width: 100,
        height: 150,
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 10,
    },
    resourceCategoryButton: {
        width: 170,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 5,
        borderRadius: 20,
        backgroundColor: '#E3C2D7',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContainer: {
        width: '80%',
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 24,
        marginBottom: 10,
        fontWeight: 'bold',
    },
    pickerSelectStyles: {
        inputIOS: {
            fontSize: 16,
            color: 'black',
            width: 340,
            height: 40,
            padding: 10,
            borderRadius: 20,
            borderWidth: 1,
            borderColor: '#979595', 
        },
        inputAndroid: {
            fontSize: 16,
            paddingHorizontal: 10,
            paddingVertical: 8,
            borderWidth: 0.5,
            borderColor: 'gray',
            borderRadius: 8,
            color: 'black',
            paddingRight: 30, 
            borderRadius: 20,
        },
    },
});

export default styles;